import type {Metadata} from "next";
import "./globals.css";
import {cn} from "@/lib/utils";
import {Inter as FontSans} from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs";
import {Toaster} from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Response tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable
                )}
            >
            <NextTopLoader
                height={2}
                color="#000"
                easing="cubic-bezier(0.53,0.21,0,1)"
            />
            <Toaster/>
            {children}
            </body>
            </html>
        </ClerkProvider>
    );
}